version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  product-service:
    build: ./product-service
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  order-service:
    build: ./order-service
    depends_on:
      - rabbitmq

  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
