version: '3'
services:
  order-service:
    build: ./order-service  # Dockerfile'ın bulunduğu dizin
    image: dockozkan/order-service:latest  # Docker Hub'da kullanılacak imaj adı ve tag
    environment:
      - RABBITMQ_HOST=rabbitmq

  product-service:
    build: ./product-service  # Dockerfile'ın bulunduğu dizin
    image: dockozkan/product-service:latest  # Docker Hub'da kullanılacak imaj adı ve tag
    environment:
      - RABBITMQ_HOST=rabbitmq

  user-service:
    build: ./user-service  # Dockerfile'ın bulunduğu dizin
    image: dockozkan/user-service:latest  # Docker Hub'da kullanılacak imaj adı ve tag
    environment:
      - RABBITMQ_HOST=rabbitmq
