apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: dockozkan/product-service:latest  # Docker Hub imajı
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
