apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: dockozkan/user-service:latest  # Docker Hub imajı
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
