apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: myregistry/user-service:latest  # Kullanacağın Docker image
          ports:
            - containerPort: 5000
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: DATABASE_URL
              value: "postgres://user:password@db-service:5432/userdb"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
